# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d13a1cdbc80bbf0f707247ec86df3b16267212faaefef9129ee084a37d8d058d99b24db95a509aaef638b9c8656838aeebd777d64bc0d7426e32d072a92a7868

test:
  secret_key_base: 52bfd527dd321ba6eb3f8abc2769f3a32da88047b0b2f02162e09e8255bc99f7f6eb68a384c8a87cf5c97de2b41b3546f25ae1221bc3e5e0cf6531e9116c099a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
